# t.sleep(0.001)
# # t.sleep(0.001)
# # t.sleep(0.001)
# # t.sleep(0.001)
# # t.sleep(0.001)
# # t.sleep(0.001)
# # t.sleep(0.001)
# # t.sleep(0.001)
# # t.sleep(0.001)# from webbrowser import Chrome
# import pyautogui as p
# import keyboard as k
# import time
# k.send("windows+r")
# time.sleep(0.1)
# p.typewrite("chrome")
# time.sleep(0.5)
# k.send("enter")
# time.sleep(0.5)
# k.send("tab")
# time.sleep(0.5)
# k.send("enter")
# time.sleep(0.5)
# k.send("ctrl+t")
# time.sleep(1)
# p.typewrite("http://172.31.1.203:8090/httpclient.html")
# time.sleep(0.5)
# k.send("enter")
# time.sleep(0.5)
# p.press("tab")
# time.sleep(1)
# k.send("down arrow")
# time.sleep(1)
# k.send("down arrow")
# time.sleep(0.5)
# k.send("enter")
# time.sleep(0.5)
# k.send("enter")


from webbrowser import Chrome
import pyautogui as p
import keyboard as k
import time
k.send("windows+r")
time.sleep(0.5)
# p.typewrite("edge")
# time.sleep(0.1)
# k.send("enter")htt
# time.sleep(0.3)
# k.send("tab")
# time.sleep(0.3)
# k.send("enter")
# time.sleep(0.3)
# k.send("ctrl+t")
# time.sleep(0.5)
p.typewrite("http://172.31.1.203:8090/httpclient.html")
time.sleep(0.3)
k.send("enter")
time.sleep(0.5)
p.press("tab")
time.sleep(0.5)
p.typewrite("bt20103083")
time.sleep(0.2)
k.send("tab")
time.sleep(0.2)
p.typewrite("QI11FM39")
time.sleep(0.1)
k.send("enter")
